# This is a basic workflow to build the springboot application and generate the docker image

name: Build Springboot Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test the workflow
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          pwd
          ls -la


